synthetic_data_params_list:
  - 'option'
  - 'n'
  - 'm'
  - 'noise_std'
  - 'redundancy_rate'
  - 'features_fill'
  - 'poly_degree'
  - 'seed'


evaluation_params_list:
  perm_importance:
    - 'explanation_rate'
    - 'n_repeats'

  iht:
    - 'explanation_rate'
    - 'k'
    - 'tol'
    - 'max_iter'
    - 'verbose'


# The parameter section itself
# Dataset params
option: 'sparse'
n: 100
m: 200
noise_std: 1
redundancy_rate: 0.5
features_fill: 'normal'
poly_degree: 1
seed: 54

explanation_rate: 0.95

n_repeats: 30

k: 150
tol: 0.001
max_iter: 1000
verbose: False